### ISSUE TITLE
Can only take food of mage table in full stacks

### ISSUE THREAD

**Issue by Neverik90** [ValorenWoW/sunstrider-core#5563] opened 2023-11-02 00:05 UTC
E.g. when you have 69 Conjured Manna Biscuits in your inventory you cant click the table and get 11 food. You have to delete 9 Conjured Manna Biscuits and can take another full stack of 20.

**Comment by z5n** [comment] 2023-11-02 01:21
duplicate of #2994

**Closed as completed by z5n** 2023-11-02 01:21 UTC
