### ISSUE TITLE
Ethereum Overlord gets killed but weapons stay behind and keep attacking you

### ISSUE THREAD

**Issue by DaturoDewitt** [ValorenWoW/sunstrider-core#4856] opened 2021-03-18 16:42 UTC
**Describe the bug**
Ethereum Overlord gets killed, but an afterimage of his weapons still exists and attacks you which you can't target.
**Character name**
DaturoDewitt

**To Reproduce**

1. Kill Etherum Overlord
2. Weapons follow you afterwards and attack you

NPC: https://tbcdb.com/?npc=20459

**Expected behavior**
Dead enemies stay dead.

**Screenshots/videos**
![grafik](https://user-images.githubusercontent.com/49022685/111663463-1ef31200-8811-11eb-969c-4b1f0b12f62d.png)

**Additional context**
Apparently it doesn't happen all the time, maybe it's a connection with any ShadowPriest spells?

**Comment by DaturoDewitt** [comment] 2021-03-18 16:46
![grafik](https://user-images.githubusercontent.com/49022685/111664155-c7a17180-8811-11eb-98f9-dfff989c4114.png)
An Horde player being followed by the weapons...

**Comment by Jerrythemagicdog** [comment] 2021-03-18 18:09
Probably not a bug, but fixed with the next update. Thanks for the issue.

**Closed as completed** 2021-03-18 18:08 UTC
