### ISSUE TITLE
The Vengeful Harbinger quest Terokar

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4851] opened 2021-03-17 11:14 UTC
tried this quest about 5x in a 3man group could never get it to work quite correctly.

after you use the stone to trigger the guardian, the packs of 3 mobs run down and sometimes don't engage the guardian... instead they run to the altar area (circle) and then reset.   If you engage 2 of the 3 the 3rd one can still reset as well.

after doing multiple waves a vengeful harbinger spawned.  killed it in the middle of the room.  did not get "kill credit" and the guardian stood around for a long time before the event seemingly ended and respawned.

on several of the subsequent attempts, i waited for harbinger to enter the circle.  upon death the guardian also died and a cut scene happens with a pink face in the altar circle area.    quest references talking to the draenei asendant, but never saw any such thing.  no ? for quest completion.  on one attempt my mouse turned into a gear for a split second during the ending animation scene but i didnt click it and subsequent attempts couldnt find the gear again.

on one attempt i did nothing an the harbinger ran to circle, and reset.  i went forward pulled it back to the circle and it half did the cut scene.  

another attempt the harbinger was dead, no cut scene, and then randomly i started getting agro warnings from the dead vengeful harbinger. 

in one instance the harbinger corpse was on the ground, but it kept changing its facing towards me... like it was still active and targetting me, but yet dead.

**Comment by Sheikthecatman** [comment] 2021-03-20 18:46
When did you attempt to complete the quest? It was recently fixed on live server. I'm unable to reproduce the issue while testing so if you could record or provide screenshots that would be great.

**Comment by michaelkittrell** [comment] 2021-03-23 04:25
pretty sure i posted the bug immediately after i spent an hour failing to complete it.

**Comment by Sheikthecatman** [comment] 2021-03-29 18:55
Quest seems to be working fine on live since last fix, so I am closing the issue.

**Closed as completed by Sheikthecatman** 2021-03-29 18:55 UTC
Labels: question
