### ISSUE TITLE
Quest Rescue OOX-09/HL! in Hinterlands bugged

### ISSUE THREAD

**Issue by Hoaas** [ValorenWoW/sunstrider-core#4762] opened 2021-03-06 13:42 UTC
**Describe the bug**
Mechanical chicken walks slowly in the air after first group of mobs. Quest is never completed, nor does it fail.

**To Reproduce**
1. Start Rescue OOX-09/HL! (in Hinterlands)
2. Protect chicken
3. A group of 3 owlkin spawns
4. Kill owlkin
5. Watch chicken continue walking
6. Chicken is following a path through the air
7. Chicken is out of viewing range
8. ....

Item: https://wowhead.com/item=8704/oox-09-hl-distress-beacon
Quest: https://wowhead.com/quest=836/rescue-oox-09-hl
NPC: https://wowhead.com/npc=7806/homing-robot-oox-09-hl

**Expected behavior**
Either that chicken continues path and spawn another gorup of mobs, before quest completes, or that it takes of and quest completes right away after first group, like the quest in Tanaris and Feralas does.

**Screenshots/videos**
NPCs are just killed.
![image](https://user-images.githubusercontent.com/414791/110208858-ca06e180-7e89-11eb-850f-195fc82a3408.png)

Chicken starts getting higher
![image](https://user-images.githubusercontent.com/414791/110208867-d8ed9400-7e89-11eb-8c0a-4be6f4ec08fa.png)

Location where chicken is too high to view (61.89, 53.84)
![image](https://user-images.githubusercontent.com/414791/110208876-e4d95600-7e89-11eb-952f-e45181dd67a0.png)

**Comment by miki-g** [comment] 2021-12-11 14:48
still broken, after first owlbeast attack fly up and disappear

**Comment by z5n** [comment] 2023-07-07 16:07
https://www.youtube.com/watch?v=SfBr4OWqrQ8 seems to be the intended behavior, current behavior just looks scuffed
quest *is* marked as completed though

**Comment by z5n** [comment] 2023-08-11 13:12
thanks, fixed with next restart

**Closed as completed** 2023-08-11 13:11 UTC
Labels: quest, confirmed
