### ISSUE TITLE
summon bugs/error messages

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4936] opened 2021-04-08 14:57 UTC
There is a summon bug where if you have received a summon, and then are summoned again before accepting the first summon...  clicking accept does nothing.  Please change this to either ignore the second summon (allowing you to take the original) or to reset the timer to full duration (2m) and make it actually work when you click accept.

Because of this bug and a general perception that many private servers have summon bugs (whether real or not) that players can become "summon bugged" where they literally can't accept any kind of summon for whatever reason until they re-log... it would be really nice if you introduce error messages if you can't accept a summon for a legitimate reason.

1.  entered too many instances 
2. do not meet the level requirements
3. requires xyz key/attunment
4. not in a raid

You get these error messages when you try to zone into an instance across the portal threshold, why don't you get these error messages when attempting to accept a summon?

**Comment by kelno** [comment] 2021-04-10 07:01
Testing now, if a player resummons already pending summon accept, this second summon has no effect and the target can still accept the first one.
I do believe there is a bug with summons since I keep hearing about "summon bug" indeed, any idea how to actually reproduce it?

**Comment by michaelkittrell** [comment] 2021-04-12 08:49
I can't say for sure that i have experienced the "can't accept summons until relog" here.  everyone's default behavior is just to relog if the summon "doesn't work".

Fixing this one should go along ways to answering the question if there is a 2nd bug.

**Comment by kelno** [comment] 2021-08-03 13:14
Closing for now as we can't reproduce.

**Comment by z5n** [comment] 2023-10-28 20:38
issue has since been fixed

**Closed as completed by z5n** 2023-10-28 20:38 UTC
