### ISSUE TITLE
Guild Logs cant be seen

### ISSUE THREAD

**Issue by gozkok** [ValorenWoW/sunstrider-core#4534] opened 2020-11-28 16:23 UTC
Hello, 

This is Umbaku. We are in "Baby Guild" as Horde and we are having a big issue of not seeing Guild Logs. We have been in touch with GMs and they have told us to open a Bug report. Could you please fix that we have big numbers of active players and we cant see anything.

**Comment by michaelkittrell** [comment] 2020-11-29 01:50
would be interesting to maybe make the guild logs avaialble on the website for guild members to see... since the in game UI is pretty limited/shit especially if you have guild repair on.

**Comment by Ironjudgment** [comment] 2020-12-02 17:25
A quick local fix is to use this macro:

/run GuildEventLog_Update()

**Comment by z5n** [comment] 2023-08-05 17:04
duplicate of #2405

**Closed as completed by z5n** 2023-08-05 17:04 UTC
Labels: core, confirmed
