### ISSUE TITLE
Holy Nova not triggering pvp

### ISSUE THREAD

**Issue by TimHoenselaar** [ValorenWoW/sunstrider-core#4943] opened 2021-04-09 17:16 UTC
Holy Nova does not trigger pvp for guards to attack a player inside a town like area 52 when it's damaging part is used to deal damage to players of the opposite faction

**Comment by Jerrythemagicdog** [comment] 2021-04-09 18:31
Thanks for the issue, duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/4872

**Closed as completed by Jerrythemagicdog** 2021-04-09 18:31 UTC
