### ISSUE TITLE
[Quest] Aldor Chain: Shutting Down Manaforge Duro

### ISSUE THREAD

**Issue by orconfig** [ValorenWoW/sunstrider-core#4979] opened 2021-04-30 14:50 UTC
Description:

Quest Shutting Down Manaforge Duro is broken.

Actual behaviour:

No gear icon at the object to interact with after acquiring the key to use. Hence cannot proceed with shutting down event and complete the quest.

Expected behaviour:

"Managofge" http://db.hellfire-tbc.com/?npc=20418 should be "usable" if you have acquired the key.

Steps to reproduce the problem:

Pick up quest. & kill the npc for the Access crystal.
Attempt to shut down the Manaforge.
Quest: https://tbcdb.com/?quest=10322

Reproduced on character: Truepewpew on 29.04.2021, to this day behavior is the same.

**Comment by tateaz17** [comment] 2021-04-30 15:30
Same thing happen to me but I do the Scryers Rep

**Comment by kelno** [comment] 2021-05-01 15:04
Can any of you give me your character name? I can interact with the console correctly when testing.

**Comment by kelno** [comment] 2021-05-01 15:31
It's fixed now on Windrunner, but I'm not sure how it did get stuck in the first place.
Dev: Console is stuck with GO_FLAG_IN_USE set, event seemingly not running. Has to be something very rare because we've been running the same script forever.

**Comment by z5n** [comment] 2023-07-07 15:56
unable to reproduce, issue has likely since been fixed

**Closed as completed by z5n** 2023-07-07 15:56 UTC
Labels: core, confirmed
