### ISSUE TITLE
Quest: Jungle Secrets, unable to talk to Lieutenant Doren

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5667] opened 2024-05-03 00:31 UTC
**Describe the bug**
In STV, as an alliance character, after saving Private Thorsen from being slaughtered by 2 of Kurzen's Agent, he lets you in on the secret mission he was trying to embark on in the form of giving you a quest called Jungle Secrets. The 1st step of Jungle Secrets is to return to the rebel camp in northern STV and talk to Lieutenant Doren there. Yet, Lieutenant Doren cannot be talked to.

**Character name**
Elillinr

**To Reproduce**

1. Follow Private Thorsen when he leaves for his patrol.
2. See him accosted and attacked by two of Kurzen's Agent. 
3. Defeat the two before Private Thorsen dies.
4. Talk to Private Thorsen.
5. Head back to rebel camp, attempt to talk to Lieutenant Doren

Quest: https://www.wowhead.com/tbc/quest=215/jungle-secrets
Private Thorsen: https://www.wowhead.com/tbc/npc=738/private-thorsen
Lieutenant Doren: https://www.wowhead.com/tbc/npc=469/lieutenant-doren
Note: Doren's stats and appearance differs significantly from what is shown on WoWhead. Different version? Half the hitpoints, and on horseback.

**Expected behavior**
There should be a dialogue option to start a longer dialogue chain in Lieutenant Doren's gossip.

**Additional context**

**Comment by Jerrythemagicdog** [comment] 2024-05-03 11:34
I can't reproduce the issue: 
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/9b075160-6c9b-4b30-ac02-c1272cdf4574)
the follow-up is also offered correctly:
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/5a380665-8503-4f50-9969-5dd8d5ab8aa7)

**Comment by Jerrythemagicdog** [comment] 2024-05-03 11:59
I've taken a closer look and found the issue using a copy of your character.
Thanks, fixed with the next update!

**Closed as completed by Jerrythemagicdog** 2024-05-03 11:59 UTC
