### ISSUE TITLE
Bestial Wrath not affecting damage of regular pet swings

### ISSUE THREAD

**Issue by Wixyz** [ValorenWoW/sunstrider-core#5056] opened 2021-10-02 13:44 UTC
Damage of regular swings during bestial wrath appear to be the same as without the buff active.
Special abilities are affected by bestial wrath and appear to be boosted by about 50% as intended.

Me and another hunter both tested and reached the same conclusion.

**Comment by kelno** [comment] 2021-10-06 09:17
Thanks for reporting, it's indeed not working as intended.

**Comment by kelno** [comment] 2021-10-06 09:19
Fixed with next server update

**Closed as completed** 2021-10-06 09:18 UTC
Labels: core, confirmed
