### ISSUE TITLE
Endless rage applying with dodge/parry/missed attacks

### ISSUE THREAD

**Issue by beefjurkey** [ValorenWoW/sunstrider-core#4698] opened 2021-02-18 17:35 UTC
Endless rage reads "you generate 25% more rage from damage dealt"
Yet it still applies to misses/parrys/dodges
We actually tested this on the target dummy too make sure its correct

**Comment by Jerrythemagicdog** [comment] 2021-02-18 20:37
No rage is generated on misses, other than that the issue is correct as long as it's not one of those misworded talents.
Thanks for the issue, fixed with next update.

**Closed as completed** 2021-02-18 20:36 UTC
Labels: confirmed
