### ISSUE TITLE
Druid - Energy regen timer

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4665] opened 2021-01-29 20:37 UTC
When a druid shapeshifts, energy regen timer should reset.

> Power Regeneration: Any effect which triggers a change in your rate of power regeneration (Mana, Rage, Energy, Focus) will now cause an immediate reward of some power at the old rate of increase, and then begin new “ticks” of power at the new rate approximately 2 seconds later. This was done to improve functionality of abilities such as Evocation and Innervate so that they did not have wasted “ticks”.
https://wowwiki.fandom.com/wiki/Patch_2.2.0?oldid=1567509

**Comment by Jerrythemagicdog** [comment] 2021-02-01 15:46
Some video footage:
https://youtu.be/HVfTsZNMTa8?t=218
https://youtu.be/HVfTsZNMTa8?t=277
https://youtu.be/HVfTsZNMTa8?t=540
https://youtu.be/HVfTsZNMTa8?t=696
https://youtu.be/Kfy65HJyiac?t=113

**Comment by kelno** [comment] 2021-02-11 17:13
Thanks. The next tick indeed should happen exactly 2s after the shift.

**Comment by kelno** [comment] 2021-02-11 18:57
I've implemented what's described in the changelog, but this is a different issue than the powershift issue reported here.

**Comment by kelno** [comment] 2021-02-11 19:00
This issue also fixed with next server update

**Closed as completed by kelno** 2021-02-11 19:00 UTC
Labels: core, confirmed

**Comment by nmagane** [comment] 2021-03-01 15:28
Hello, I believe this "fix" is inaccurate - Powershifting to 60 energy has been known and documented on forums through original Vanilla to original TBC. It is a crucial part of feral's dps in PvE and PvP.
https://web.archive.org/web/20080915204905/http://elitistjerks.com/f31/t10533-druid_cat_dps-_powershifting/
It is discussed on this forum thread that the patch (According to the dates, most likely patch 2.2.0) did in fact cause it to change (as was proven by the footage) - but it was never stated whether it was intended or not. 


> Power Regeneration: Any effect which triggers a change in your **rate of power regeneration** (Mana, Rage, Energy, Focus) will now cause an immediate reward of some power at the old rate of increase, and then begin new “ticks” of power at the new rate approximately 2 seconds later. This was done to improve functionality of abilities such as Evocation and Innervate so that they did not have wasted “ticks”.

This patch, as you stated, has no effect on druid's energy tick. Powershifting (aka the talent furor), does not affect the RATE of energy regeneration, it GIVES energy.
So even though this patch is from after the forum posts were made, I do not think it meant to affect druid's shifting. 

Regardless of whether it's intended or not - for over half of the expansion, it worked the old way.
I understand if you wish to remain "accurate/blizzlike" - but this change only negatively impacts an already mediocre spec when it was originally meant for other purposes (like listed above, evocation/innervate/adrenaline rush ticks). 
I apologize if this shouldn't be posted here, as it's not really a "bug" but rather a plea to not ruin a spec many people enjoyed playing on Sunstrider for the sake of following ambiguous patch notes. 
After all, most people playing this realm are preparing for classic - and we do not know how this will behave there yet.

**Comment by trickdaemon** [comment] 2021-03-01 16:24
Definitely an error in my opinion, this behavior does not occur on other servers such as Smolderforge or back in Vanilla/Tbc nor wow classic.  I play a feral in classic and the feral theorycrafting discord (https://discord.gg/zjgGckr) has confirmed this is not as intended and you should be able to receive 60 energy after a powershift during/before an energy tick (or 80 when you have wolfshead helm equipped.)

Video proof: (edit: this is a private server, just like all the other videos posted as "proof" above.) 
https://youtu.be/hxBsT8JycBo?t=25 receives 60 energy after powershifting as the tick of energy applies after/during furor. 

Please look into remedying this, thank you!

**Comment by trickdaemon** [comment] 2021-03-01 18:54
Smoking gun obtained: 2.4.3 intended behavior has been removed by you guys and prepatched to 2.2 behavior as listed in the wikilink used as proof in the initial post.  Please return this fix to the original, intended state of 2.4.3 :).  The 2.2 energy bug (as currently in Endless server) has been removed and updated in 2.4.3. 

![image](https://user-images.githubusercontent.com/79805241/109544312-63eb1a80-7a95-11eb-970f-cf552a670146.png)
src: https://web.archive.org/web/20080913075822/http://druid.wikispaces.com/ToskksDPSGearMethod#toc6
