### ISSUE TITLE
Cannot top off mage food stack

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5422] opened 2023-10-23 18:04 UTC
**Describe the bug**
Clicking a mage food table will not top off any stacks you have. For example if I had a 10 stack of mage food with 3 stacks of 20 totaling 70, if I click the table nothing would happen. I have to delete the stack of 10 and then grab another stack to get the full 80 food.

**Comment by z5n** [comment] 2023-10-23 20:23
duplicate of #2994

**Closed as completed by z5n** 2023-10-23 20:23 UTC
