### ISSUE TITLE
Pyrewood village mobs and quest mobs are elite. Their day/night transformation doesn't work and it duplicates the mobs.

### ISSUE THREAD

**Issue by pj4041** [ValorenWoW/sunstrider-core#5265] opened 2023-09-14 01:06 UTC
Mobs in Pyrewood Village such as Moonrage watcher / sentry / tailor / elder / etc. should be human during the day (and called Pyrewood watcher/sentry/...), and worgen during the night.

On this server there is always 2 mobs of the same type together as if one is transformed and one is not.
For example Pyrewood watcher and Moonrage watcher walking together. Pyrewood sentry and Moonrage sentry walking together.

Additionally, the mobs for the quest here, called Pyrewood Ambush, should also no longer be elite in TBC.

moonrage NPCs
1924, 1896, 1893, 1770, 3533, 3531, 1892, 3529, 1769, 1779, 1782

pyrewood NPCs
3528, 1895, 1894, 3532, 3530, 1891

**Comment by Jerrythemagicdog** [comment] 2023-09-17 19:13
Thanks for the issue!
I can't reproduce duplicated spawns, can you provide more detail?

Worgen creatures being elites fixed with the next update.

**Closed as completed** 2023-09-17 19:13 UTC

**Comment by pj4041** [comment] 2023-09-18 14:40
@Jerrythemagicdog thanks for looking into this, 

for the duplicates - I was leveling and I saw that there's always 2 mobs paired together, more specifically 2 different versions of the same mob. 
_For example Pyrewood watcher and Moonrage watcher walking together. Pyrewood sentry and Moonrage sentry walking together._
That's why I assumed that instead of the transformed unit, you are tracking both versions simultaneously. I could have been wrong of course, but it was just oddly specific.

for elites I hope you included the mobs for the quest here that I mentioned, it's called "Pyrewood Ambush" and it's some councilmen that spawn in waves.

**Comment by Jerrythemagicdog** [comment] 2023-09-18 20:03
Thanks for the details!
Yes, the councilmen and mayor are included.

**Comment by pj4041** [comment] 2023-09-19 17:48
@Jerrythemagicdog here it is! Has to be some sort of duplicates

![pyrewood_duplicates](https://github.com/SunstriderEmu/BugTracker/assets/101959663/fb506590-efa2-45f3-8560-ac767e197542)

**Comment by Jerrythemagicdog** [comment] 2023-09-20 22:23
Thanks for the details!
I still can't reproduce the issue on my local server and I must be really unlucky because each time I check on the live realm the issue is not present haha.
We'll look into it!

**Comment by pj4041** [comment] 2023-09-22 01:16
no worries, now that they're not elites I am sure this is really not an issue for anyone really :)
thanks again for fixing the elites thing and sorry for wasting dev time on such a random issue
