### ISSUE TITLE
Debuff timer increasing while offline

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5291] opened 2023-09-27 22:42 UTC
Debuffs are increasing overtime while offline for long periods of time.

![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/4a3616b6-f096-4fc9-9120-12d13cee0f8a)
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/64a407ad-295a-4f80-8595-d302522151c6)

**Comment by Jerrythemagicdog** [comment] 2023-09-28 00:36
Thanks for the issue!
I can't reproduce it, the auras expire correctly when offline.

**Comment by hotdogsteven** [comment] 2023-09-28 01:18
Characters: Gage, Tanna

**Comment by kelno** [comment] 2023-09-28 11:03
Just stay logged out for a month and this will happen

**Comment by kelno** [comment] 2023-09-28 11:21
Fixed with next update

**Closed as completed** 2023-09-28 11:22 UTC
Labels: core, confirmed
